service: search-api
provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  environment:
    OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
    OPENSEARCH_USERNAME: ${env:OPENSEARCH_USERNAME}
    OPENSEARCH_PASSWORD: ${env:OPENSEARCH_PASSWORD}
functions:
  api:
    handler: src.main.handler
    events:
      - httpApi:
          path: /docs  # Swagger UI用
          method: get
      - httpApi:
          path: /openapi.json  # OpenAPI仕様用
          method: get
      - httpApi:
          path: /search  # 検索API
          method: get
      - httpApi:
          path: /{proxy+}  # その他のパス
          method: '*'
    layers:
      - Ref: PythonRequirementsLambdaLayer
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    zip: true
