service: search-api
provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  environment:
    OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
    OPENSEARCH_USERNAME: ${env:OPENSEARCH_USERNAME}
    OPENSEARCH_PASSWORD: ${env:OPENSEARCH_PASSWORD}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - Fn::GetAtt: [BooksTable, Arn]
package:
  individually: true 
  patterns:
    - '!**'  # まず全部除外
    - 'requirements.txt'  # requirements.txtも必要
functions:
  api:
    handler: src.main.handler
    package:
      include:
        - src/main.py
        - src/schemas.py
        - src/utils.py
    events:
      - httpApi:
          path: /docs
          method: get
      - httpApi:
          path: /openapi.json
          method: get
      - httpApi:
          path: /search
          method: get
      - httpApi:
          path: /books
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
    layers:
      - Ref: PythonRequirementsLambdaLayer
  syncToOpensearch:
    handler: src.dynamodb_stream.handler
    package:
      include:
        - src/dynamodb_stream.py
        - src/schemas.py
        - src/utils.py
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [BooksTable, StreamArn]
    layers:
      - Ref: PythonRequirementsLambdaLayer
resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Books
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    zip: true
